#!/bin/bash

# Install Ruby dependencies
sudo apt-get update
sudo apt-get install -y build-essential autoconf libssl-dev libyaml-dev zlib1g-dev libffi-dev libgmp-dev rustc

/usr/local/bin/mise trust /workspaces/ruby-lab/mise.toml && /usr/local/bin/mise install

# Install Ruby Gems
echo "Starting install of Ruby Gems using bundle: /usr/local/bin/mise exec ruby -- bundle install"
echo "NOTE: This command takes a while to kick in, don't panic if it looks like devpod creation froze!"

/usr/local/bin/mise exec ruby -- bundle install --verbose
